- type: faction
  name: "Божественный Мандат Сол"
  id: DSM
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: НЕТ
    Один из двух главных игроков в секторе Тайпан.
    Подходит для новых игроков, представляет основной опыт ALT-SPACE.
  buttonColor: DarkSlateBlue
  description: |
    Неофеодальный осколок Империи, некогда простиравшейся среди звезд,
    напоминающий древнюю Священную Римскую Империю.
    
    Сейчас Мандат изолирован в секторе и направлен Кайзером, чтобы
    защитить зону от бездарного Дворянина, допустившего заражение
    социалистической заразой — Лигой Рабочих Нового Полумесяца.
    
    Десятилетиями эти гиганты сражаются за контроль над сектором.
    Авианосец «Каунтсмен» прибыл в Тайпан, чтобы закрепиться и
    в очередной раз выбить силы юнионистов из этой зоны.
    
    Мандат молит Святых и Кайзера о победе. Высшие роли занимают
    дворяне, где Дом Кирхейс стоит на вершине иерархии.
    Дом Вопросов (ДВ) следит за верностью слуг, быстро карая за
    любые признаки измены или нелояльности режиму.
    
    Свободные люди или дворяне, рискнувшие выступить против, быстро
    оказываются под надзором ДВ или исчезают. Другие расы допускаются
    в ряды, но часто сталкиваются с жесткой дискриминацией.
  color: "#9FED58"
  weight: 8
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: dsm

- type: faction
  name: "Лига Рабочих Нового Полумесяца"
  id: NCWL
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: НЕТ
    Один из двух главных игроков в секторе Тайпан.
    Подходит для новых игроков, представляет основной опыт ALT-Space.
  buttonColor: "#a46106"
  description: |
    Военизированное синдикалистское правительство, рожденное в
    результате восстания против угнетателей из дома Оливир.
    
    Они стали крупной силой, способной соперничать с Мандатом.
    Действуя с прифронтовой станции Порт-Белреска, они ведут
    войну против имперских псов, стремящихся их поработить.
    Фронтовые силы — это Ополчение во главе с Вольгиным Гришинградом.
    
    Лига стремится к равенству всех рабочих, независимо от их вида.
    Их убеждения выкованы суровыми квотами дома Оливир.
    
    Некогда Лига освободила весь сектор, но победа была недолгой
    из-за прибытия дома Кирхейс. Сегодня в их рядах зреет раскол,
    но диссиденты боятся Министерства Внутренней Бдительности.
  color: "#9FED58"
  weight: 7
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: ncwl

- type: faction
  name: "Тяжелая Индустрия Шинохара"
  id: SHI
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: 3 ЧАСА / 1 РАУНД
    Промышленный гигант. Геймплей: торговля и технологии.
    Ожидайте жесткие квоты на прибыль и налеты пиратов.
  buttonColor: DarkSlateGray
  description: |
    Последний из корпоративных гигантов и реликт старого мира.
    Шинохара — это последняя «настоящая корпорация» в наши дни.
    
    Отрезанные от основного пузыря, они сохраняют свою догму
    мира беспрецедентной жадности, инноваций и эффективности.
    Для многих их методы кажутся более «чуждыми», чем сами пришельцы.
    
    Владея секретами NanoTrasen, SHI является лидером в области
    археотехнологий. Они управляют логистикой, добычей ресурсов и
    даже производством космических судов в секторе.
    
    Используя верфи «Прометей» и станцию «Тацумото», они торгуют со
    всеми сторонами, балансируя в спирали военных конфликтов ради
    сохранения своих корпоративных интересов.
  color: "#9FED58"
  weight: 6
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: shi

- type: faction
  name: "Коалиция Свободных Станций Тайпана"
  id: TFSC
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: 3 ЧАСА / 1 РАУНД
    Четыре корпорации под одним флагом ради прибыли и свободы.
    Вас могут нанять, но союзники могут предать ради денег.
  buttonColor: DarkRed
  description: |
    Конгломерат независимых групп: пиратов, каперов, утилизаторов
    и врачей, которые без зазрения совести заберут ваши органы.
    
    Среди них: Gorlex Security, Interdyne Pharm и Cyberdawn Tech.
    Их часто сравнивают с экосистемой падальщиков за их методы.
    
    Коалиция выросла из Синдиката Каперов — перебежчиков, которые
    желали жить вне хватки главных фракций сектора.
    
    После разрушения Фрипорта эти группы разошлись еще сильнее.
    Теперь они часто сражаются друг с другом за лучшие контракты.
  color: "#9FED58"
  weight: 5
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: tfsc

- type: faction
  name: "Тайпано-Атирианский Пакт"
  id: TAP
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: 10 ЧАСОВ / 3 РАУНДА
    Маленький аванпост в системе Тайпан.
    Скрытая станция всего на четыре роли.
    Играйте на свой страх и риск.
  buttonColor: DarkGreen
  description: |
    Кочевое сообщество племен звездоплавателей, состоящее из
    семей различного происхождения: духовных Арабет, воинов Аль-Сейк,
    материалистов Издари и предприимчивых семей Туккер.
    
    Они живут на переоборудованном тяжелом грузовом судне,
    перемещаясь с места на место, чтобы выжить. У кочевников
    репутация наемников, контрабандистов и азартных игроков.
  color: "#9FED58"
  weight: 4
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: fourfamilies

- type: faction
  name: "Ополчение Святого Ромэна"
  id: SRM
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: 10 ЧАСОВ / 3 РАУНДА
    Фракция очень редко присутствует в системе Тайпан.
    Только для специальных спавнов в середине раунда.
  buttonColor: Black
  description: |
    Бывшее подразделение Корпуса Имперского Повиновения.
    SRM нашли свою идентичность в поиске сбежавших «активов»
    Империи и «вербовке» новых рабов для своих господ.
    
    Это гильдия работорговцев с божественным уклоном. Они часто
    забредают в Тайпан из системы Доминион, чтобы захватить жертв
    для нужд имперского строительства.
  color: "#9FED58"
  weight: 3
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: srm

- type: faction
  name: "Центральная Власть Сол"
  id: ATH
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: 10 ЧАСОВ / 3 РАУНДА
    Фракция очень редко присутствует в системе Тайпан.
    Только для специальных спавнов в середине раунда.
  buttonColor: Black
  description: |
    Авторитарный режим, наследник Мандата, ныне ставший фашистским.
    Их винят в смерти Кайзера, и они ведут гражданскую войну.
    
    Авторитат сосредоточен на контроле и жестоких завоеваниях
    для искоренения всех, кто связан с псионическими феноменами.
    Они верят, что псионика угрожает поглотить всю галактику.
    
    Являясь сверхдержавой человечества, они дают экономическую
    свободу не-псионикам, но жестко подавляют любое инакомыслие,
    переписывая историю под свои текущие нужды.
  color: "#ffffed"
  weight: 2
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: csa

- type: faction
  name: "Колониальные Минитмены"
  id: TSP
  description: |
    Самопровозглашенное агентство правопорядка на фронтире.
    Существуют лишь на скудные пожертвования и конфискат.
    
    Плохое снаряжение и набор кадров из бедных слоев делают их
    уязвимыми для коррупции, которую крупные силы сектора даже
    не пытаются искоренить из-за нехватки ресурсов.
  color: "#9FED58"
  weight: 1
  enabled: false
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: tsp