name: Close PRs on master

on:
  pull_request_target:
    types: [ opened, ready_for_review ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{github.head_ref == 'master' || github.head_ref == 'main' || github.head_ref == 'develop'}}
    
    steps:    
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Спасибо за вклад в наш репозиторий. К сожалению, похоже, что вы отправили pull request из ветки `master`. Мы рекомендуем ознакомиться с [документацией по работе с git](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html).\n\nВы можете перенести текущие изменения из ветки `master` в другую ветку, создав новую ветку ([branching](https://git-scm.com/docs/git-branch)) и затем сбросив ветку `master` ([resetting](https://git-scm.com/docs/git-reset))."
